language: ruby

cache:
  bundler: true

rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - 2.3.3
  - 2.4.0
  - jruby-19mode
  - ruby-head
  - jruby-head

notifications:
  email: false

sudo: false

branches:
  only:
    - master
    - development

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head